In [1]:
import numpy as np

Problem1:

In [5]:
arr1 = np.eye(3) * 9
arr1

array([[9., 0., 0.],
       [0., 9., 0.],
       [0., 0., 9.]])

Problem2:

In [7]:
arr2 = np.ones((7,7))
arr2[1:6,1:6] = 0
arr2[3,3] = 5
arr2

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 5., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

Problem3:

In [10]:
n = int(input())
arr3 = np.arange(1, n+1)
arr4 = np.ones((n,1)) * arr3
arr4


array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

Problem4:

In [24]:
arr5 = np.random.randint(0,101,(5,5))
print(f"Original Array:\n {arr5}")
# max in each row:
print(f"Max: {arr5.max(axis=1)}")
# sum of each column:
print(f"Sum: {arr5.sum(axis=0)}")
# mean of the matrix:
print(f"Mean: {arr5.mean()}")
# new matrix:
arr6 = (arr5 > 50).astype(int)
print(f"After Masking:\n {arr6}")

Original Array:
 [[ 7 71  4  8  5]
 [34 65 29 17 86]
 [85 37 29 62 39]
 [59 26 81 22 61]
 [69 44 32 45  3]]
Max: [71 86 85 81 69]
Sum: [254 243 175 154 194]
Mean: 40.8
After Masking:
 [[0 1 0 0 0]
 [0 1 0 0 1]
 [1 0 0 1 0]
 [1 0 1 0 1]
 [1 0 0 0 0]]


Problem 5:

In [43]:
arr7 = np.arange(1,31).reshape(6,5)
print(arr7)
# 1:
print(f"The small 2x2 square containing:\n {arr7[2:4,0:2]}")
# 2:
print(f"elemets:\n {arr7[[0, 1, 2, 3], [1, 2, 3, 4]]}")
# 3:
print(f" Rows with even indices:\n {arr7[[0,2,4]]}")


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
The small 2x2 square containing:
 [[11 12]
 [16 17]]
elemets:
 [ 2  8 14 20]
 Rows with even indices:
 [[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]


Problem 6:


In [48]:
scores = np.array([45, 88, 92, 30, 50, 76, 99, 12, 65])
# 1- Use Boolean Indexing to filter and print only the passing grades (>= 50)
passed = scores[scores>=50]
print(f"Passed {passed}")

# 2- check if any student got a perfect score of 100
print(np.any(scores == 100))

# 3- check if all students passed
print(len(passed) == len(scores))

Passed [88 92 50 76 99 65]
False
False
